### PR TITLE
Bump Go, Helm and various dependencies

### PR DESCRIPTION
**Pull request by macedogm**
Bump Go to 1.19, Helm to 3.10.3 and various Go dependencies.

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Comment by macedogm** [comment]
@cwayne18 and @brandond this is quite a huge bump. How can we test it to be sure that it doesn't break anything, please?

**Review by brandond — APPROVED** [review]
LGTM. I'm pretty sure the versions here will be overridden in klipper-helm at build time, but it's good to get everything bumped.

The plugin itself is super minimal so I'm not too worried about the bumps here.

**Comment by macedogm** [comment]
@brandond thanks for merging the PR. Can you please cut a new tag so we can propagate these updates (I don't have permissions to do it)?

**Comment by brandond** [comment]
@macedogm tagged as v0.1.3

**Pull request merged**
